# Generated by Django 6.1.1 on 2026-09-20 00:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramBot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('token', models.CharField(blank=True, max_length=120)),
                ('username', models.CharField(blank=True, max_length=64)),
                ('webhook_secret', models.CharField(blank=True, max_length=80)),
                ('webhook_url', models.CharField(blank=True, max_length=300)),
                ('connected_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, max_length=300)),
                ('last_update_at', models.DateTimeField(blank=True, null=True)),
                ('messages', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, editable=False, help_text='Who created this row. Empty means the system did.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, editable=False, help_text='Who retired this row. Empty means the system did.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, help_text='Who last changed this row. Empty means the system did.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Telegram bot',
            },
        ),
    ]
