# Generated by Django 6.1.1 on 2026-09-14 02:38

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('confidence_gate', models.PositiveSmallIntegerField(default=85, help_text="Below this, Ma'at says so and offers to look further.", validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('mentions_before_publish', models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1)])),
                ('max_followup_questions', models.PositiveSmallIntegerField(default=2, validators=[django.core.validators.MaxValueValidator(5)])),
                ('questions_per_visitor_per_hour', models.PositiveSmallIntegerField(default=20)),
                ('daily_question_cap', models.PositiveIntegerField(default=2000)),
                ('raw_text_retention_days', models.PositiveSmallIntegerField(default=30)),
                ('embedding_model', models.CharField(blank=True, max_length=120)),
                ('answer_model', models.CharField(blank=True, max_length=120)),
                ('interpreter_model', models.CharField(blank=True, max_length=120)),
                ('created_by', models.ForeignKey(blank=True, editable=False, help_text='Who created this row. Empty means the system did.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, editable=False, help_text='Who retired this row. Empty means the system did.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, help_text='Who last changed this row. Empty means the system did.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Application settings',
                'verbose_name_plural': 'Application settings',
            },
        ),
    ]
