# Generated by Django 6.1.1 on 2026-09-15 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsettings', '0002_countrycoverage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countrycoverage',
            name='status',
        ),
        migrations.AddField(
            model_name='countrycoverage',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
