# Generated by Django 6.1.1 on 2026-09-14 02:38

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
from pgvector.django import VectorExtension
import pgvector.django.indexes
import pgvector.django.vector
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # pgvector must exist before any column uses its type.
        VectorExtension(),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('door', models.CharField(choices=[('upload', 'Direct upload'), ('feed', 'RSS or Atom feed'), ('api', 'Developer API'), ('connector', 'Other connector')], default='upload', max_length=20)),
                ('address', models.URLField(blank=True)),
                ('homepage', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('cadence_minutes', models.PositiveIntegerField(default=360)),
                ('is_active', models.BooleanField(default=True)),
                ('last_polled_at', models.DateTimeField(blank=True, null=True)),
                ('country', models.ForeignKey(blank=True, help_text='Leave empty for a source that applies globally.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sources', to='core.country')),
                ('created_by', models.ForeignKey(blank=True, editable=False, help_text='Who created this row. Empty means the system did.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, editable=False, help_text='Who retired this row. Empty means the system did.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, help_text='Who last changed this row. Empty means the system did.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='IngestionRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='running', max_length=12)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('documents_seen', models.PositiveIntegerField(default=0)),
                ('documents_added', models.PositiveIntegerField(default=0)),
                ('documents_updated', models.PositiveIntegerField(default=0)),
                ('chunks_written', models.PositiveIntegerField(default=0)),
                ('error', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, help_text='Who created this row. Empty means the system did.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, editable=False, help_text='Who retired this row. Empty means the system did.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, help_text='Who last changed this row. Empty means the system did.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='knowledge.source')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('title', models.CharField(max_length=500)),
                ('identifier', models.CharField(max_length=1000)),
                ('url', models.URLField(blank=True, max_length=1000)),
                ('published_at', models.DateField(blank=True, null=True)),
                ('fetched_at', models.DateTimeField(blank=True, null=True)),
                ('fingerprint', models.CharField(db_index=True, max_length=64)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_current', models.BooleanField(default=True)),
                ('parser_version', models.PositiveIntegerField(default=1)),
                ('original', models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/')),
                ('byte_size', models.PositiveBigIntegerField(default=0)),
                ('content_type', models.CharField(blank=True, max_length=120)),
                ('language', models.CharField(default='en', max_length=12)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='core.country')),
                ('created_by', models.ForeignKey(blank=True, editable=False, help_text='Who created this row. Empty means the system did.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, editable=False, help_text='Who retired this row. Empty means the system did.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, help_text='Who last changed this row. Empty means the system did.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='knowledge.source')),
            ],
            options={
                'ordering': ['-published_at', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Chunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('kind', models.CharField(choices=[('fragment', 'Fragment'), ('card', 'Card')], db_index=True, default='fragment', max_length=10)),
                ('chunk_index', models.PositiveIntegerField(default=0)),
                ('text', models.TextField()),
                ('retrieval_text', models.TextField(blank=True)),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(blank=True, null=True)),
                ('page_number', models.PositiveIntegerField(blank=True, null=True)),
                ('heading_path', models.CharField(blank=True, max_length=500)),
                ('embedding_model', models.CharField(blank=True, max_length=120)),
                ('is_current', models.BooleanField(db_index=True, default=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, help_text='Who created this row. Empty means the system did.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, editable=False, help_text='Who retired this row. Empty means the system did.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, help_text='Who last changed this row. Empty means the system did.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='knowledge.document')),
            ],
            options={
                'ordering': ['document', 'chunk_index'],
                'indexes': [models.Index(fields=['document', 'is_current'], name='knowledge_c_documen_058900_idx'), django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='chunk_search_vector_gin'), pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='chunk_embedding_hnsw', opclasses=['vector_cosine_ops'])],
                'constraints': [models.UniqueConstraint(fields=('document', 'kind', 'chunk_index'), name='chunk_position_is_unique')],
            },
        ),
        migrations.AddIndex(
            model_name='source',
            index=models.Index(fields=['is_active', 'door'], name='knowledge_s_is_acti_3439b3_idx'),
        ),
        migrations.AddIndex(
            model_name='source',
            index=models.Index(fields=['country'], name='knowledge_s_country_90b660_idx'),
        ),
        migrations.AddIndex(
            model_name='ingestionrun',
            index=models.Index(fields=['source', '-started_at'], name='knowledge_i_source__75abc7_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['source', 'is_current'], name='knowledge_d_source__fa338e_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['is_current', 'published_at'], name='knowledge_d_is_curr_6cc99a_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['country'], name='knowledge_d_country_6de154_idx'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.UniqueConstraint(fields=('source', 'identifier', 'version'), name='document_version_is_unique'),
        ),
    ]
