# Generated by Django 6.1.1 on 2026-09-15 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0002_document_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='failure_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='source',
            name='http_etag',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='source',
            name='http_last_modified',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='source',
            name='last_error',
            field=models.TextField(blank=True),
        ),
    ]
