# Generated by Django 6.1.1 on 2026-09-15 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0003_source_failure_count_source_http_etag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='brand',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='source',
            name='collection',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='source',
            name='logo_url',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='source',
            name='short',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='source',
            name='subject',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='source',
            name='verification',
            field=models.CharField(default='listed', max_length=16),
        ),
    ]
