# Generated by Django 6.1.1 on 2026-09-15 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0004_source_brand_source_collection_source_logo_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
