# Generated by Django 6.1.1 on 2026-09-15 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0005_alter_source_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='scope',
            field=models.CharField(default='general', max_length=16),
        ),
    ]
