# Generated by Django 6.1.1 on 2026-09-15 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0006_source_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='auth',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='source',
            name='response_sample',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='response_sample_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='schema',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
