# Generated by Django 6.1.1 on 2026-09-15 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0007_source_auth_source_response_sample_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='door',
            field=models.CharField(choices=[('upload', 'Direct upload'), ('feed', 'RSS or Atom feed'), ('api', 'Developer API'), ('pages', 'Public web pages'), ('connector', 'Other connector')], default='upload', max_length=20),
        ),
    ]
