# Generated by Django 6.1.1 on 2026-09-14 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='state',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
