# Generated by Django 6.1.1 on 2026-09-14 13:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0002_conversation_state'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='visitor_key',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='rumour',
            name='reporter_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['visitor_key', '-created_at'], name='verificatio_visitor_d189fb_idx'),
        ),
    ]
