# Generated by Django 6.1.1 on 2026-09-14 00:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('code', models.CharField(max_length=3, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('numeric', models.CharField(blank=True, max_length=3)),
                ('minor_units', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('symbol', models.CharField(blank=True, max_length=8)),
                ('created_by', models.ForeignKey(blank=True, editable=False, help_text='Who created this row. Empty means the system did.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, editable=False, help_text='Who retired this row. Empty means the system did.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, help_text='Who last changed this row. Empty means the system did.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Currencies',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('iso2', models.CharField(max_length=2, unique=True)),
                ('iso3', models.CharField(max_length=3, unique=True)),
                ('numeric_code', models.CharField(max_length=3, unique=True)),
                ('phone_code', models.CharField(blank=True, max_length=10)),
                ('flag_emoji', models.CharField(blank=True, max_length=8)),
                ('created_by', models.ForeignKey(blank=True, editable=False, help_text='Who created this row. Empty means the system did.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, editable=False, help_text='Who retired this row. Empty means the system did.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, help_text='Who last changed this row. Empty means the system did.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='countries', to='core.currency')),
            ],
            options={
                'verbose_name_plural': 'Countries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TimeZone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, help_text='Who created this row. Empty means the system did.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, editable=False, help_text='Who retired this row. Empty means the system did.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, help_text='Who last changed this row. Empty means the system did.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Time zone',
                'verbose_name_plural': 'Time zones',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StateProvince',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=128)),
                ('kind', models.CharField(blank=True, max_length=64)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='core.country')),
                ('created_by', models.ForeignKey(blank=True, editable=False, help_text='Who created this row. Empty means the system did.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, editable=False, help_text='Who retired this row. Empty means the system did.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, help_text='Who last changed this row. Empty means the system did.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('timezone', models.ForeignKey(blank=True, help_text='Left empty by the seed: no offline dataset maps subdivisions to zones.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='states', to='core.timezone')),
            ],
            options={
                'verbose_name': 'State or province',
                'verbose_name_plural': 'States and provinces',
                'ordering': ['name'],
            },
        ),
        migrations.AddIndex(
            model_name='currency',
            index=models.Index(fields=['code'], name='core_curren_code_fcefac_idx'),
        ),
        migrations.AddIndex(
            model_name='currency',
            index=models.Index(fields=['name'], name='core_curren_name_567cfb_idx'),
        ),
        migrations.AddConstraint(
            model_name='currency',
            constraint=models.CheckConstraint(condition=models.Q(('code__regex', '^[A-Za-z]{3}$')), name='currency_code_three_letters'),
        ),
        migrations.AddIndex(
            model_name='country',
            index=models.Index(fields=['name'], name='core_countr_name_5737bb_idx'),
        ),
        migrations.AddIndex(
            model_name='country',
            index=models.Index(fields=['iso2'], name='core_countr_iso2_f80f3f_idx'),
        ),
        migrations.AddConstraint(
            model_name='country',
            constraint=models.CheckConstraint(condition=models.Q(('iso2__regex', '^[A-Za-z]{2}$')), name='country_iso2_two_letters'),
        ),
        migrations.AddConstraint(
            model_name='country',
            constraint=models.CheckConstraint(condition=models.Q(('iso3__regex', '^[A-Za-z]{3}$')), name='country_iso3_three_letters'),
        ),
        migrations.AddConstraint(
            model_name='country',
            constraint=models.CheckConstraint(condition=models.Q(('numeric_code__regex', '^[0-9]{3}$')), name='country_numeric_three_digits'),
        ),
        migrations.AddIndex(
            model_name='timezone',
            index=models.Index(fields=['name'], name='core_timezo_name_64c482_idx'),
        ),
        migrations.AddIndex(
            model_name='stateprovince',
            index=models.Index(fields=['country', 'name'], name='core_statep_country_3dc207_idx'),
        ),
        migrations.AddIndex(
            model_name='stateprovince',
            index=models.Index(fields=['country', 'code'], name='core_statep_country_389724_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='stateprovince',
            unique_together={('country', 'code')},
        ),
    ]
